### ISSUE TITLE
for pip use on corporate networks

### ISSUE THREAD

**Issue by qw3r3wq** [SweptWasTaken/swepts-toolkit#1]
Hi, in addition to yours, I would recommend adding --user:
`pip install --user youtube-dl`

;) that will install your pip libs into `~/.local/[bin|lib|....]` then you can setup git and clone it between hosts ;) without need for virtenv ;) and in the end just add it to the **PATH**

**Comment by SweptWasTaken** [comment]
> Hi, in addition to yours, I would recommend adding --user: `pip install --user youtube-dl`
> 
> ;) that will install your pip libs into `~/.local/[bin|lib|....]` then you can setup git and clone it between hosts ;) without need for virtenv ;) and in the end just add it to the **PATH**

That's a good idea! Added!
